### ISSUE TITLE
Question: Use together with Polyglot maven

### ISSUE THREAD

**Issue by paulvi** [repaint-io/maven-tiles#61]
Polyglot maven https://github.com/takari/polyglot-maven makes it possible to define build in other languaes

Have you tried to use tiles together with polyglot, e.g. import tiles written in other dialects

**Comment by talios** [comment]
I haven't yet, but it was something I was interested in trying. I suspect
we would have to write out a processed tile pom based on a polyglot
reader/writer. However since the tile xml is not a valid pom (due to some
custom elements) we might not be able to do so.

I'd think we would want to always publish as xml for interoperability if we
did.

-- sent from the hips, via an android.

**Comment by paulvi** [comment]
@talios Mark, could you update https://github.com/takari/polyglot-maven/issues/82 a bit after trying

**Comment by rvowles** [comment]
Looks like we are suffering http://rvowl.es/1U1qz5c

**Comment by paulvi** [comment]
@rvowles Richard, what is putting head into sand like strauss is about?

@talios I have run into 1dt issue https://github.com/takari/polyglot-maven/issues/83

**Comment by rvowles** [comment]
@paulvi - jason immediately closed your ticket.

**Comment by talios** [comment]
Did some experimentation, is seems the Groovy dialect is the only one that currently works as expected, the rest cause a raft of issues - mostly they ignore the `<extensions>` element of a plugin, and due to the nature of Mojo configuration ( just a raw DOM node in the Model ) not all of write out the correct config as part of the converter.  I updated that ticket with https://github.com/takari/polyglot-maven/issues/82#issuecomment-211826469 with examples of my experiment.

As it stands, tiles works with the Groovy dialect, but not the others.

**Comment by paulvi** [comment]
@talios well, reading this afterwards. Yes others people say also say that Groovy flavor is more stable as of now https://github.com/takari/polyglot-maven/issues/82#issuecomment-211923763
