### ISSUE TITLE
Support using a range for tile version

### ISSUE THREAD

**Issue by udalrich** [repaint-io/maven-tiles#82]
I would like to be able to specify a range of versions for a tile, so that as the tile is improved, everything that uses it gets the updated version rather than having to find the uses and update them.  This would look like

                <configuration>
                    <tiles>
                        <tile>me.tile:mySuperTile:[1.0.0,2.0.0)</tile>
                    </tiles>
                </configuration>

using the standard [maven version range rules](
https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges)

**Comment by talios** [comment]
On 16 Oct 2018, at 8:42, udalrich wrote:


    <tile>me.tile:mySuperTile:[1.0.0,2.0.0)</tile>



That's supported out of the box - are you seeing behaviour that shows otherwise?



"The ease with which a change can be implemented has no relevance at all to whether it is the right change for the (Java) Platform for all time." — Mark Reinhold.

Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by udalrich** [comment]
I was certain that I tried this and it didn't work.  I just tried again and it did.  Maybe I did [1.0.0-2.0.0) instead, which makes some sense but is wrong.
